export const Prompts = [
    "What’s your name and where are you from?",
    "Describe your morning routine.",
    "What do you usually eat for breakfast?",
    "Do you prefer working or studying?",
    "What’s your favorite hobby?",
    "How do you usually spend your weekends?",
    "Describe a typical day in your life.",
    "What time do you usually go to sleep?",
    "What’s your favorite meal to cook?",
    "Do you like mornings or nights more?",
    "Tell me about your hometown.",
    "What languages are spoken in your country?",
    "What is a typical dish in your culture?",
    "What are some important holidays in your country?",
    "How do people greet each other in your culture?",
    "Describe a traditional celebration or festival.",
    "What’s your favorite place in your city?",
    "What is something tourists should try in your area?",
    "How do people usually get around your city?",
    "What’s the weather like where you live?",
    "Why are you learning this language?",
    "How do you usually practice speaking?",
    "What’s the hardest part of learning a language?",
    "What languages do you want to learn next?",
    "Do you like studying grammar or vocabulary more?",
    "How often do you practice?",
    "What’s your favorite word in your target language?",
    "How do you remember new words?",
    "Do you learn better by listening or reading?",
    "What apps or tools do you use to learn?",
    "What countries have you visited?",
    "What country do you want to visit most?",
    "Describe your last vacation.",
    "Do you prefer mountains or beaches?",
    "What do you usually pack for a trip?",
    "How do you prepare for a trip abroad?",
    "What do you like to do when you travel?",
    "What was the most interesting food you tried while traveling?",
    "Do you prefer traveling alone or with others?",
    "What’s your dream destination?",
    "What do you do for work or study?",
    "What was your favorite subject in school?",
    "Do you prefer online or in-person learning?",
    "What’s your dream job?",
    "What skills would you like to learn?",
    "Describe your ideal work environment.",
    "How do you stay motivated?",
    "Do you like working in a team or alone?",
    "What’s something you learned recently?",
    "How do you manage your time?",
    "What’s your favorite movie?",
    "Who is your favorite musician or band?",
    "Do you prefer coffee or tea?",
    "What’s your favorite type of food?",
    "What’s the best book you’ve read?",
    "Do you enjoy sports?",
    "What kind of music do you like?",
    "What social media do you use most?",
    "Do you prefer cats or dogs?",
    "What’s your favorite season?",
    "If you had a superpower, what would it be?",
    "If you could meet any celebrity, who would it be?",
    "If you won the lottery, what would you buy first?",
    "If you could live anywhere, where would you go?",
    "If you could speak any language instantly, which one?",
    "What would you do with a day off and no responsibilities?",
    "Would you rather travel to the past or the future?",
    "If you had one wish, what would you wish for?",
    "If you were famous, what would you be famous for?",
    "What would your ideal weekend look like?",
    "What makes you happy?",
    "How do you deal with stress?",
    "What do you do when you feel sad?",
    "Who do you admire most?",
    "What’s something you're proud of?",
    "What motivates you?",
    "What are you afraid of?",
    "What does success mean to you?",
    "What values are most important to you?",
    "How do you define a good friend?",
    "Describe your family.",
    "Do you prefer small gatherings or big parties?",
    "What qualities do you look for in a friend?",
    "How do you celebrate your birthday?",
    "Do you enjoy meeting new people?",
    "How do you stay in touch with friends?",
    "What do you like to do with your friends?",
    "Have you ever had a pen pal?",
    "What’s the best advice someone gave you?",
    "What’s your love language?",
    "What’s your favorite app?",
    "How often do you watch TV or movies?",
    "What’s your favorite website?",
    "Do you use AI tools or chatbots?",
    "Do you play video games?",
    "What technology could you not live without?",
    "Do you prefer books or eBooks?",
    "What’s a cool gadget you’ve used recently?",
    "How do you usually learn online?",
    "What app do you spend the most time on?"
  ];